-- Codificador BPS para Contribuyentes (Versión 37, 26/06/2026)
-- Crea/actualiza las tablas de códigos oficiales de BPS usadas en la nómina.
-- Migración idempotente: ON CONFLICT DO UPDATE permite re-aplicarla sin error.

-- Nuevas tablas de catálogo
CREATE TABLE IF NOT EXISTS "naturaleza_juridica" (
    "codigo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "naturaleza_juridica_pkey" PRIMARY KEY ("codigo")
);
CREATE TABLE IF NOT EXISTS "causales_egreso" (
    "codigo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "causales_egreso_pkey" PRIMARY KEY ("codigo")
);
CREATE TABLE IF NOT EXISTS "vinculos_funcionales" (
    "codigo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "vinculos_funcionales_pkey" PRIMARY KEY ("codigo")
);
CREATE TABLE IF NOT EXISTS "tipos_remuneracion" (
    "codigo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "tipos_remuneracion_pkey" PRIMARY KEY ("codigo")
);
CREATE TABLE IF NOT EXISTS "seguros_salud" (
    "codigo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "seguros_salud_pkey" PRIMARY KEY ("codigo")
);
CREATE TABLE IF NOT EXISTS "exoneraciones_aporte" (
    "codigo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    CONSTRAINT "exoneraciones_aporte_pkey" PRIMARY KEY ("codigo")
);

-- Causal de egreso (BPS Tabla 9) registrada en el contrato al dar la baja.
ALTER TABLE "contracts" ADD COLUMN IF NOT EXISTS "causalEgresoCod" INTEGER;

-- Datos oficiales del codificador
-- tipos_aporte (13 códigos)
INSERT INTO "tipos_aporte" ("codigo", "nombre") VALUES
  (1, 'IC — Industria y Comercio'),
  (2, 'CI — Civil'),
  (3, 'RU — Rural'),
  (4, 'CT — Construcción'),
  (5, 'Notarial'),
  (6, 'Bancaria'),
  (7, 'TD — Trabajo a Domicilio'),
  (8, 'Escolar'),
  (11, 'Servicios Personales'),
  (12, 'Militar'),
  (13, 'Policial'),
  (14, 'Unión Postal'),
  (48, 'Servicio Doméstico')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";

-- naturaleza_juridica (35 códigos)
INSERT INTO "naturaleza_juridica" ("codigo", "nombre") VALUES
  (1, 'Empresa Unipersonal'),
  (2, 'Sociedad Responsabilidad Limitada'),
  (3, 'Sociedad Anónima'),
  (4, 'Sociedad de hecho'),
  (5, 'Sociedad colectiva'),
  (6, 'Sociedad en comandita simple'),
  (7, 'Sociedad de capital'),
  (8, 'Sociedad civil'),
  (9, 'Asociación'),
  (10, 'Cooperativa de consumo'),
  (11, 'Cooperativa de ahorro'),
  (12, 'Cooperativa de producción'),
  (13, 'Sucursal de empresa'),
  (14, 'Sociedad de fomento'),
  (15, 'Cooperativa agropecuaria'),
  (16, 'Organismo paraestatal'),
  (17, 'Sucesores de'),
  (18, 'Organización social'),
  (19, 'Cooperativa de vivienda'),
  (20, 'Fundaciones, Corporaciones'),
  (21, 'Edificio en propiedad horizontal'),
  (22, 'Consorcio'),
  (23, 'Grupo de interés económico'),
  (24, 'Sociedad accidental'),
  (25, 'Organismo público'),
  (26, 'Sociedad civil de producción'),
  (27, 'Sociedad ganadera'),
  (28, 'Sociedad en comandita por acciones'),
  (29, 'Núcleo familiar'),
  (30, 'Empresa extranjera'),
  (31, 'Fideicomiso'),
  (32, 'Sociedad Agraria de Responsabilidad Ltda.'),
  (33, 'Asociación Agraria de Responsabilidad Ltda.'),
  (34, 'Cooperativa Social'),
  (35, 'Sociedad Accionista Simplificada (Vig. 01/01/2020)')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";

-- causales_egreso (21 códigos)
INSERT INTO "causales_egreso" ("codigo", "nombre") VALUES
  (1, 'Voluntario'),
  (2, 'Despido'),
  (3, 'Fallecimiento'),
  (4, 'Termino de Contrato'),
  (5, 'Jubilación'),
  (7, 'Oficio (para uso exclusivo del B.P.S.)'),
  (8, 'Baja por cambio de titular, fusión, escisión de empresas o rotación de personal entre empresas según acuerdo registrado ante MTSS, modificación de vínculo de promoción del empleo.'),
  (10, 'Término de mandato'),
  (11, 'Cese por motivos reglamentarios (docentes)'),
  (12, 'Cese por edad'),
  (13, 'Cese por mala conducta'),
  (15, 'Fallecimiento en acto directo'),
  (22, 'Cesante. Inicio sub. por incapacidad física T o P y/o jubilación por incapacidad física'),
  (23, 'Cesante - Inicia cobro Incentivo'),
  (31, 'Cese de Subsidio'),
  (32, 'Cese de Incentivo'),
  (33, 'Cese de comisión'),
  (50, 'Otros motivos'),
  (80, 'Baja por omisión de declaración en nóminas (para uso exclusivo del B.P.S.)'),
  (98, 'Dado de baja por error'),
  (99, 'Dado de alta por error')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";

-- vinculos_funcionales (168 códigos)
INSERT INTO "vinculos_funcionales" ("codigo", "nombre") VALUES
  (1, 'Patrón unipersonal'),
  (2, 'Socio con actividad'),
  (3, 'Socio sin actividad'),
  (4, 'Socio cooperativista'),
  (5, 'Socio/sucesor/patrón unipersonal/cónyuge colaborador/representante legal SAS/administ rador SAS con actividad aporta por otra empresa'),
  (6, 'Director/Administrador con remuneración'),
  (7, 'Director/Administrador sin remuneración'),
  (8, 'Síndico con remuneración'),
  (9, 'Síndico sin remuneración'),
  (10, 'Cónyuge o Concubino/a colaborador/a (Mod. descripción - Vigencia 02/2008)'),
  (12, 'Empleado'),
  (13, 'Empleado temporario o zafral'),
  (14, 'Empleado a la orden'),
  (15, 'Obrero'),
  (16, 'Obrero temporario o zafral'),
  (17, 'Obrero a la orden'),
  (20, 'Cargo político, de particular confianza o cargo electivo'),
  (21, 'Cesante - percibe subsidio'),
  (22, 'Cesante - percibe incentivo'),
  (23, 'Personal en subsidio por enfermedad'),
  (24, 'Personal en subsidio por maternidad y/o paternidad ***** (modificado con fecha 25/11/2013 Ley)'),
  (25, 'Personal en seguro por desempleo'),
  (26, 'Reserva del cargo'),
  (27, 'No tributa aportes previsionales al B.P.S'),
  (28, 'Prácticos. Aporte personal a cargo de Sociedad de Prácticos, Puerto o Corporación Prácticos de Río'),
  (29, 'Prácticos. Aporte patronal a cargo de Agencia Marítima'),
  (30, 'Funcionarios de Aeronavegación de Pluna'),
  (31, 'Personal en Subsidio Transitorio por incapacidad parcial'),
  (32, 'Trabajadores extranjeros en régimen de Traslado Temporario'),
  (33, 'Patrón-Cónyuge/Socio/Director no cotizante de contribuciones especiales al B.P.S'),
  (34, 'Administrador de empresa unipersonal o sociedad de hecho (por cese d e patrón)'),
  (35, 'Personal con contrato de práctica laboral'),
  (36, 'Personal con becas de trabajo'),
  (37, 'Personal con contrato de aprendizaje'),
  (38, 'Personal con contrato de aprendizaje simple'),
  (40, 'Personal con pasantía laboral. No cotizante de contribuciones especiales al B.P.S.'),
  (41, 'Obrero a Domicilio'),
  (42, 'Tallerista'),
  (43, 'Ayudante de Tallerista'),
  (44, 'Tallerista - Exclusivo para la Distribución de aportes'),
  (45, 'Ayudante de Taller – Exclusivo para la Distribución de aportes'),
  (46, 'Socio/Sucesor/Patrón Unipersonal/Cónyuge Colaborado r con act., aporta únicamente computo especial'),
  (47, 'Cargo electivo/Ministro de Estado/Miembro de Org. del Art.220, opta por la asignación de Pasividad (art.102 Ley 16.134 del 20/09/1990)'),
  (48, 'Trabajador extranjero en Zona Franca. No cotizante de contribucio nes especiales al BPS'),
  (49, 'Personal jornalero no estable de la estiba'),
  (50, 'Sucesor con actividad'),
  (51, 'Sucesor sin actividad'),
  (52, 'Miembro Honorario. Junta Electoral, Médicos y Odontólogos Salud Pública y Docentes Honorarios Facultad de Odontología (Per.1921 a 1941)'),
  (53, 'Funcionario Dirección Nacional de Arquitectura del M.T.O.P.'),
  (54, 'Profesionales del deporte'),
  (55, 'Trabajadores Packing'),
  (56, 'Personal en Subsidio Transitorio, amparado por BPS'),
  (57, 'Adscriptos a Presidencia de la República'),
  (58, 'Régimen de retiro incentivado (Ley 17930)'),
  (60, 'Personal de Embajada'),
  (61, 'Contratos a Término – Ley 17.556'),
  (63, 'Actividades Comunitarias comprende Dec. 231/03 y 274/05 y Ley 18240 apoyo Inserción Laboral'),
  (64, 'Trabajadores panaderos y de catering eventuales (RD44 -33/2004 y 2-23/2005 y 5-2/2009)'),
  (65, 'Bancos del Estado, personal contratado Ley 17.556 sin aportes BPS'),
  (66, 'Becarios y Pasantes en la Administración Pública'),
  (67, 'Funcionario del Ministerio de Defensa y/o Interior, no incluido en FONASA'),
  (68, 'Cargo político o particular confianza del Ministerio de Defensa y/o Interior, no incluido en FONASA'),
  (69, 'No tributa aportes CESS jubilatorias, tributa CESS destinadas a SNIS'),
  (70, 'Categoría 1 (Capitán, Jefe de Máq.) Personal de la pesca remunerado "a la parte"'),
  (71, 'Categoría 2 (1° Oficial, Maquinista, Patrón) Personal de la pesca rem. "a la parte"'),
  (72, 'Categoría 3 (2° Oficial, 2°Pat. 2° Máq. Com. Telegr) Personal de la pesca rem. "a la parte"'),
  (73, 'Categoría 4 (3° Oficial, 3° Maquinista, 1° Electricista, Frigorista, 3er. Patrón) Personal de la pesca remunerado "a la parte"'),
  (74, 'Categoría 5 (4° Oficial, 2° Electricista, 4° Maquinista ) Personal de la pesca remunerado "a la parte”'),
  (75, 'Categoría 6 (Cocinero, Engrasador, Marinero, Limpiador, Ayudante de cocina, Contramaestre, 1° y 2° Mecánico) Personal de la pesca remunerado "a la parte"'),
  (76, 'Docente de Enseñanza Privada'),
  (77, 'Jubilado beneficiario SNIS'),
  (78, 'En comisión, beneficiario al SNIS'),
  (79, 'Trabajador Objetivo Empleo, Programa MTSS'),
  (80, 'Personal en subsidio – uso exclusivo BOE'),
  (81, 'Trabajadores extranjeros en régimen de traslado temporario del MERCOSUR'),
  (82, 'Trabajador de Industria y Comercio incorporado a Caja Bancaria Ley 18.396'),
  (83, 'Subsidio especial de inactividad compensada'),
  (84, 'Régimen de Retiro Incentivado (Ley 17930) sin aporte al Seguro de Salud'),
  (85, 'Personal Policial Ejecutivo'),
  (86, 'Personal Policial de Apoyo'),
  (87, 'Becarios y Pasantes en la Administración Pública con derecho al FONASA'),
  (88, 'Escribanos'),
  (89, 'Profesionales'),
  (90, 'En comisión, no beneficiario de SNIS'),
  (91, 'Personal Excedentario'),
  (92, 'Titulares Servicios Personales no Profesionales'),
  (93, 'Cuidadoras de INAU (Alta cod. Vigencia 12/2011)'),
  (94, 'Contrato laboral Inc. 02 a 15 Administración Central (Alta código Vigencia 01/2011)'),
  (95, 'Pasivos nal.2° art.1° Ley 18731, Aportes SNIS (Alta código Vigencia 07/2012)'),
  (96, 'Profesionales del Deporte (no aplica Dec. 199/011) (Alta cód. Vigencia 08/2011)'),
  (97, 'Trabajador NO DEPENDIENTE sin declaración de servicios por parte de la empresa'),
  (98, 'Trabajador DEPENDIENTE sin declaración de servicios por parte de l a empresa'),
  (99, 'Becarios Programa Yo estudio y trabajo (Alta código Vigencia 07/2012)'),
  (100, 'Director con Remuneración GIE (Grupo de Interés Económico) (Alta código Vigencia 01/01/1960)'),
  (101, 'Titular Serv. Personales Prof. y no Profesionales – Subsidios (Alta código Vigencia 01/07/2012)'),
  (102, 'Escribanos en Subsidio (Alta código Vigencia 01/08/2012)'),
  (103, 'Jubilado (Reingreso a la actividad) Ley 19006 del 16/11/2012 (Alta código. Vigencia 01/06/2013)'),
  (104, 'Trabajador joven Art.7° Ley 19006 del 16/11/2012 (alta código Vigencia 01/06/2013)'),
  (105, 'Primera Experiencia Laboral en empresa privada – Ley 19133 (Alta código Vigencia 01/10/2013)'),
  (106, 'Práctica Laboral para egresados – Ley 19133 (Alta código Vigencia 01/10/2013)'),
  (107, 'Trabajo protegido y Promovido Joven – Ley 19133 (Alta código Vigencia 01/10/2013)'),
  (108, 'Práctica Formativa en empresas con remuneración – Ley 19133 (Alta código Vigencia 01/10/2013)'),
  (109, 'Práctica Formativa en empresas sin remuneración – Ley 19133 (alta código Vigencia 01/10/2013)'),
  (110, 'Primera Experiencia Laboral en el Estado – Ley 19133 (alta código vigencia 01/10/2013)'),
  (111, 'Primera Experiencia Laboral en Personas Públicas No Estatales – Ley 19133 (alta código vigencia 01/10/2013)'),
  (112, 'Trabajador con Jubilación Parcial – Ley 19.160 (alta código vigencia 01/02/2014)'),
  (113, 'Subsidio Cuidados Parentales – Ley 19.161 (alta código vigencia 01/11/2013)'),
  (114, 'Asistentes Personales Art. 25 Ley 18.651 (alta código vigencia 01/09/2014)'),
  (115, 'Asistente Personal – Sistema Cuidados Ley 19353 (alta código vigencia 01/0 8/2016)'),
  (116, 'Primera experiencia Laboral en temporada Decreto 458/016 (alta código vigencia 01/12/2016 - 30/04/2017, 01/11/2017-31/03/2018, 01/11/2018–30/04/2019)'),
  (117, 'Promoción de Empleo - Ley 19689 del 29/10/2018 (alta código vigencia 01/01/2019)'),
  (118, 'Personal incluido en Ley 19.787 - jornalero no estable de la estiba'),
  (119, 'Trabajador Comprendido Ley 19691 del 29/10/2018 (alta código vigencia 18/11/2018)'),
  (120, 'Administrador SAS'),
  (121, 'Director con remuneración SAS'),
  (122, 'Director sin remuneración SAS gravado'),
  (123, 'Profesional universitario informático no cotizante CESS (art.4º Dec.258/007)'),
  (124, 'Representante legal SAS'),
  (125, 'Cabotaje (Capitán, Jefe de Máquina) Marina Mercante Nacional'),
  (126, 'Cabotaje (1° Oficial, 1° Maquinista, 1° Patrón) Marina Mercante Nacional'),
  (127, 'Cabotaje (2° Oficial, 2° Patrón, 2° Maquinista, Comisario, Telegrafista) Marina Mercante Nacional'),
  (128, 'Cabotaje (3° Oficial, 2° Comisario, 3° Maquinista, 1° Electricista, 3° Patrón, Frigorista) Marina Mercante Nacional'),
  (129, 'Cabotaje (4° Oficial, 2° Electricista, 4° Maquinista, Mayordomo, Contramaestre, Mecánico) Marina Mercante Nacional'),
  (130, 'Cabotaje (Cocinero, Pañalero, 1° Mozo, 2° Cocinero, Engrasador, Foguista, Marinero, Mozo, Limpiador, Ayudante de cocina, Carpintero, Farolero) Marina Mercante Nacional'),
  (131, 'Director sin remuneración SAS no gravado'),
  (132, 'Administrador/Representante Legal SAS aporta por otra empresa, con FONASA por esta empresa'),
  (133, 'Oportunidad laboral – Programa Uruguay impulsa'),
  (134, 'Contrato joven varón sin personas a cargo jornada completa - Ley 19973'),
  (135, 'Contrato joven varón sin personas a cargo jornada parcial - Ley 19973'),
  (136, 'Contrato joven mujer o con personas a cargo jornada completa - Ley 19973'),
  (137, 'Contrato joven mujer o con personas a cargo jornada parcial - Ley 19973'),
  (138, 'Primera experiencia laboral en empresa privada jornada completa - Ley 19973'),
  (139, 'Primera experiencia laboral en empresa privada jornada parcial - Ley 19973'),
  (140, 'Primera experiencia laboral exoneración de aportes patronales - Ley 19973'),
  (141, 'Práctica laboral egresados - Ley 19973'),
  (142, 'Trabajo protegido joven - Ley 19973'),
  (143, 'Trabajo protegido joven subsidio diferencial - Ley 19973'),
  (144, 'Práctica formativa en empresas con remuneración - Ley 19973'),
  (145, 'Práctica formativa en empresas sin remuneración - Ley 19973'),
  (146, 'Primera experiencia laboral en el Estado - Ley 19973'),
  (147, 'Primera experiencia laboral en Personas Públicas No Estatales - Ley 19973'),
  (148, 'Contrato mayor 45 años sin personas a cargo jornada completa - Ley 19973'),
  (149, 'Contrato mayor 45 años sin personas a cargo jornada parcial - Ley 19973'),
  (150, 'Contrato mayor 45 años con personas a cargo jornada completa - Ley 19973'),
  (151, 'Contrato mayor 45 años con personas a cargo jornada parcial - Ley 19973'),
  (152, 'Trabajo protegido mayor 45 años - Ley 19973'),
  (153, 'Trabajo protegido mayor 45 años subsidio diferencial - Ley 19973'),
  (154, 'Trabajador comprendido en art. 40 Ley 19973 sin personas a cargo jornada completa'),
  (155, 'Trabajador comprendido en art. 40 Ley 19973 sin personas a cargo jornada parcial'),
  (156, 'Trabajador comprendido en art. 40 Ley 19973 con personas a cargo jornada completa'),
  (157, 'Trabajador comprendido en art. 40 Ley 19973 con personas a cargo jornada parcial'),
  (158, 'Programa Accesos - Art. 242 Ley 19.996'),
  (159, 'Programa Accesos - Artículo 242, Ley 19.996 - Exoneración de aportes patronales'),
  (160, 'Personal de Embajada reconocimiento retroactivo'),
  (161, 'Titular con actividad sin aporte jubilatorio Ley 20.130'),
  (162, 'Titular jubilado con actividad y aporte AFAP ley 20.130'),
  (163, 'Trabajador con jubilación parcial flexible Ley 20.130'),
  (164, 'Becario de posgrado de investigación financiado por ANII o Udelar con aporte jubilatorio'),
  (165, 'Becario de posgrado de investigación financiado por ANII o Udelar sin aporte jubilatorio y con FONASA'),
  (166, 'Personal de consulados, embajadas, representaciones diplomática s extranjeras y organismos internacionales'),
  (167, 'Ley 20130 - Trabajadores de representaciones de la República en el extranjero y en organismos internacionales con sede fuera del país (art 229), o dependientes fuera del país (art 3, numeral 6)'),
  (168, 'Director con remuneración SAS con actividad sin aporte jubilatorio Ley 20.130'),
  (169, 'Director con remuneración SAS jubilado con actividad y aporte AFAP ley 20.130'),
  (170, 'Tec. o prof. de TI cotizante CESS - ley 20191'),
  (171, 'Tec. o prof. de TI no cotizante CESS - ley 20191'),
  (172, 'Programa yo estudio y trabajo sector privado, ley 19973 (desde 01/2024)'),
  (173, 'Programa yo estudio y trabajo sector privado Sub diferencial, ley 19973 (desde 01/2024)'),
  (174, 'Trabajador uruguayo contratado por organismo internacional con sede fuera del pa ís, ley 20130 * Tenga o no actividad. ** Incluye a condóminos. *** Sin relación de dependencia. Monotributo Dec.199/07 Vig. 07/2007; Empresa Unipersonal común y Rural Ley 18246 Vig. 02/2008. Incluye situación de Unión Libre con act. en empresa rural (comprobada) a efectos de la prestación de pasividad. **** Incluye a turnantes de panadería ***** Para Activos y Seguro Conv.')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";

-- tipos_remuneracion (6 códigos)
INSERT INTO "tipos_remuneracion" ("codigo", "nombre") VALUES
  (1, 'Mensual: cobra por mes (incluye fictos patronales).'),
  (2, 'Jornalero: cobra por jornal. Se incluye a quién cobra por hora.'),
  (3, 'Destajista: cobra por tarea realizada.'),
  (4, 'A comisión: cobra exclusivamente por comisiones'),
  (5, 'Mixta: régimen compuesto por un sueldo básico mensual más una comisión'),
  (6, 'Sin remuneración')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";

-- seguros_salud (42 códigos)
INSERT INTO "seguros_salud" ("codigo", "nombre") VALUES
  (1, 'Beneficiarios con hijos sin cónyuge o concubino a cargo'),
  (2, 'Con afiliación mutual por otra empresa con hijos sin cónyuge o concubino a cargo'),
  (3, 'Sin Fonasa, ni prestaciones de actividad (ex seguro convencional)'),
  (4, 'Otro'),
  (5, 'Acumulación de actividades con hijos menores/discapacitado a cargo'),
  (6, 'Empleado en subsidio (enfermedad, maternidad, desempleo)'),
  (7, 'Empleado en subsidio a cargo del Seguro Convencional o Caja de Auxilio'),
  (8, 'Empleado amparado al Banco de Seguros del Estado'),
  (9, 'Contribuyente no beneficiario de afiliación mutual. Ejs: Socios de sociedades personales, patronos de unipersonal con más de un empleado, sin cuota mutual por cumplir menos de 13 jornales o percibir menos de 1,25 BPC'),
  (10, 'Contribuyente rural hasta 500 hás., con hijos sin cónyuge o concubino a cargo'),
  (11, 'Afiliación Mutual por Convenio'),
  (12, 'Cobertura por MSP - Decreto 231/2003'),
  (14, 'Afiliados sin beneficios de actividad'),
  (15, 'Beneficiarios sin hijos sin cónyuge o concubino a cargo'),
  (16, 'Beneficiarios con hijos con cónyuge o concubino a cargo'),
  (17, 'Beneficiarios sin hijos con cónyuge o concubino a cargo'),
  (18, 'Contribuyente rural hasta 500 has sin hijos sin cónyuge o concubino a cargo.'),
  (19, 'Contribuyente rural hasta 500 has con hijos y cónyuge o concubino a cargo'),
  (20, 'Contribuyente rural hasta 500 has sin hijos con cónyuge o concubino a cargo'),
  (21, 'Socios vitalicios con hijos sin cónyuge o concubino a cargo'),
  (22, 'Socios vitalicios sin hijos sin cónyuge o concubino a cargo'),
  (23, 'Socios vitalicios con hijos y cónyuge o concubino a cargo'),
  (24, 'Socios vitalicios sin hijos con cónyuge o concubino a cargo'),
  (25, 'Acumulación de actividades, sin hijos a cargo'),
  (26, 'Acumulación de actividades con hijos y cónyuge o concubino a cargo'),
  (27, 'Acumulación de actividades sin hijos con cónyuge o concubino a cargo'),
  (28, 'Con afiliación mutual por otra empresa, sin hijos sin cónyuge o concubino a cargo'),
  (29, 'Con afiliación mutual por otra empresa con hijos y cónyuge o concubino a cargo'),
  (30, 'Con afiliación mutual por otra empresa sin hijos con cónyuge o concubino a cargo'),
  (31, 'Afiliación mutual con hijos a cargo sin cony/conc. Aporte gradual hasta 31/12/2014'),
  (32, 'Afiliación mutual Sin hijos a cargo sin cony/conc. Aporte gradual hasta 31/12/2014'),
  (33, 'Afiliación mutual Con hijos a cargo con cony/conc. Aporte gradual hasta 31/12/2014'),
  (34, 'Afiliación mutual Sin hijos a cargo con cony/conc. Aporte gradual hasta 31/12/2014'),
  (35, 'Afiliación mutual por otra empresa con hijos sin cony/conc. Aporte gradual hasta 31/12/2014'),
  (36, 'Afiliación mutual por otra empresa sin hijos sin cony/conc. Aporte gradual hasta 31/12/2014'),
  (37, 'Afiliación mutual por otra empresa con hijos con cony/conc. Aporte gradual hasta 31/12/2014'),
  (38, 'Afiliación mutual por otra empresa sin hijos con cony/conc. Aporte gradual hasta 31/12/2014'),
  (39, 'Empleado en subsidio. Aporte gradual hasta 31/12/2014'),
  (40, 'Contribuyente no beneficiario afiliación mutual. Aporte gradual hasta 31/12/2014'),
  (41, 'Empleado amparado a BSE. Aporte gradual hasta 31/12/2014'),
  (42, 'Servicios personales sin SNIS con prestaciones actividad (Alta cód. vigencia 01/2012)'),
  (99, 'Tributa SNS por Servicio Personal')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";

-- exoneraciones_aporte (9 códigos)
INSERT INTO "exoneraciones_aporte" ("codigo", "nombre") VALUES
  (1, 'Se aplica exoneración de la empresa'),
  (2, 'Reconversión laboral (Art. 330, Ley 16.320)'),
  (3, 'Se aplica exon. Máx. (hasta el 6% a partir del 1/7/95) por integrar la industria manufacturera (Ley 16.697)'),
  (4, 'No se aplica exoneración de industria manufacturera (Ley 16.697)'),
  (5, 'Se aplica exon. intermedia o mixta por integrar parcialmente actividades manufactureras (Ley 16697 y Decreto Reglamentario.)'),
  (6, 'Exento de aportes excepto Seguro de Salud (Art. 4 Lit. C Ley 16.565)'),
  (7, 'Exoneración de aportes patronales Ley 16.873 del 01/10/97'),
  (8, 'Exoneración aportes personales por percibir las prestaciones del régimen de jub. por ahorro individual obligatorio (art.6 Ley 16713)'),
  (9, 'No tiene exoneración de aportes')
ON CONFLICT ("codigo") DO UPDATE SET "nombre" = EXCLUDED."nombre";
